### ISSUE TITLE
System info version

### ISSUE THREAD

**Issue by krispayne** [jamf/Mac-Asset-Tag#1]
I get this error when running the script:

`WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.3 instead of 10.11.3. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.`

The script finishes and submits as desired, so it's not pressing.

**Comment by ghost** [comment]
I've looked up this error before. It's being thrown by Tk/Cocoa. A deprecated means of checking the system version is still being called by the framework (Gestalt). It hasn't been updated to use the alternative method recommended in the error.

This is non-fatal error that gets thrown in the logs on systems running 10.10+. Annoying, but harmless.
